---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-icap-svc-account
  labels:
    app.kubernetes.io/name: shared-icap-svc-account

---
apiVersion: v1
kind: Secret
metadata:
  name: pullsecrets-ociconfigjson
  labels:
    app.kubernetes.io/name: pullsecrets-ociconfigjson
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "this line is a placeholder for the tpl-helper"
